apiVersion: apps/v1
kind: Deployment
metadata:
  name: jai-deployment
  labels:
    myapp: jai
spec:
  replicas: 1
  selector:
    matchLabels:
      myapp: jai
  template:
    metadata:
      labels:
        myapp: jai
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
