apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-jai
spec:
  volumes:
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: pv-claim-jai
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/log/nginx"
          name: nginx-logs
