apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-jai
spec:
  storageClassName: manual
  volumeName: pv-volume-jai
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
