apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jai-rc
  labels: 
    app: myapp 
spec:
  template:
    metadata:
      name: jai-pod
      labels: 
        myapp: jai
    spec:
      containers:
      - name: web
        image: nginx 
  replicas: 4
  selector: 
    matchLabels:
      myapp: jai 
