apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-jai
spec:
  selector:
    matchLabels:
      app: postgres-jai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-jai
    spec:
      containers:
      - image: postgres:latest
        name: database
        env: 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-jai
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: pv-claim-jai
          
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-jai
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres-jai 
